### ISSUE TITLE
Add the StarWars faker

### ISSUE THREAD

**Issue by mrstebo** [mrstebo/FakerDotNet#52]
See the documentation [here](https://github.com/stympy/faker/blob/master/doc/v1.9.1/star_wars.md)

**Comment by BenCoden** [comment]
i am getting a 404 error 
![image](https://user-images.githubusercontent.com/42153520/47609127-bec46100-da06-11e8-9524-3c7627eeaafc.png)

**Comment by mrstebo** [comment]
Ah! Looks like they moved the documentation @BenCoden 😅
