### ISSUE TITLE
Add the Vehicle faker

### ISSUE THREAD

**Issue by mrstebo** [mrstebo/FakerDotNet#59]
See the documentation [here](https://github.com/stympy/faker/blob/master/doc/vehicle.md)

**Comment by snoozins** [comment]
I'll make a start on this one.

**Comment by snoozins** [comment]
Still going on this one

Code mostly complete, few missing tests and needs a clean up. 

https://github.com/snoozins/FakerDotNet/tree/vehicle-faker

**Comment by mrstebo** [comment]
Looks good so far 👍 

Those fields underneath `Data` in the `VehicleFaker` class can also be marked with `readonly` 😉
