### ISSUE TITLE
localization support

### ISSUE THREAD

**Issue by Hameds** [mrstebo/FakerDotNet#89]
Although this is a great idea and works in English, I suggest localization support so this package can be used in other languages

**Comment by mrstebo** [comment]
That is one of my aims. But I wanted to get the most valuable faker modules done in English first so that it can be implemented and tested quickly.

I think before v1.0.0 we'll have localisation support in place. Any feedback on how we can implement this would be more than welcome 😁

**Comment by Hameds** [comment]
I think you need to move data files from the project's cs files. You can easily use `json` format for each data file with the specific language (something like this `Names.en-US.json`) 

This way people can contribute to json data files and the project doesn't have to recompile every time
